[build]
  base = "notizen-app"
  command = "npm run build"
  publish = "out"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[functions]
  directory = "netlify/functions"
  external_node_modules = ["@prisma/client"]
  node_bundler = "esbuild"

# Next.js spezifische Einstellungen
[build.environment]
  NEXT_USE_NETLIFY_EDGE = "true"
  NODE_VERSION = "18"
  NEXT_PRIVATE_TARGET = "server"

# Next.js spezifische Redirects
[[redirects]]
  from = "/_next/*"
  to = "/_next/*"
  status = 200

[[redirects]]
  from = "/api/*"
  to = "/api/*"
  status = 200

# Fallback für Client-side Routing
[[redirects]]
  from = "/*"
  to = "/200.html"
  status = 200 